apiVersion: gitisking/v1
version: v2.1.0
metadata:
  name: stock-service
  version: v2.1.0
  repo: https://github.com/ARAldhafeeri/stock-service-config.git
  devBaseURL: https://localhost:3000/stock/dev/
  stageBaseURL: https://localhost:3000/stock/stage/
  prodBaseURL: https://localhost:3000/stock/prod/
  language: nodejs
  description: " Manages inventory stock levels, updates, and availability."
actualState:
  lastChecked: "2024-09-23T12:00:00Z"
  status: true
  details:
    pricingService:
      status: true
      message: "Handshake successful with Pricing Service"
    restockService:
      status: true
      message: "Handshake successful with Restock Service"
desiredState:
  pricingService:
    sync: strict
    repo: https://github.com/ARAldhafeeri/pricing-service-config.git
  restockService:
    sync: strict
    repo: https://github.com/ARAldhafeeri/restock-service-config.git